:memo: Add Badges in README.md
swsnu/swppfall2022-team5 pull request #11
Opened 2022-11-02 11:31 UTC by lees741

2022-11-02 12:14 UTC, JuTaK97 approved these changes

2022-11-03 06:32 UTC, shp7724 requested changes

2022-11-03 06:32 UTC, shp7724 commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=swsnu_swppfall2022-team5&metric=alert_status)](https://sonarcloud.io/summary/new_code?id=swsnu_swppfall2022-team5) [![
소나클라우드 커버리지는 지워주세용

2022-11-05 07:19 UTC, shp7724 approved these changes

2022-11-05 16:31 UTC, merged